package com.example.ui

import androidx.compose.ui.graphics.Color

data class AppThemeColors(
    val backgroundGradient: List<Color>,
    val headerAccentColor: Color,
    val primaryTextColor: Color,
    val secondaryTextColor: Color,
    val glassBackgroundColor: Color,
    val glassBorderColor: Color,
    val countTextColor: Color,
    val positiveColor: Color,
    val negativeColor: Color,
    val iconContainerColor: Color,
    val iconBorderColor: Color,
    val iconTintColor: Color,
    val incrementGradients: List<Color>,
    val incrementShadow: Color,
    val decrementGradientsActive: List<Color>,
    val decrementGradientsInactive: List<Color>,
    val decrementShadow: Color,
    val resetContainerColor: Color,
    val resetContentColor: Color,
    val resetBorderColor: Color,
    val sheetBackgroundColor: Color
)

fun getAppThemeColors(theme: AppTheme, count: Int): AppThemeColors {
    return when (theme) {
        AppTheme.LIGHT -> AppThemeColors(
            backgroundGradient = listOf(Color(0xFFF8FAFC), Color(0xFFFFFFFF)),
            headerAccentColor = Color(0xFF3B82F6),
            primaryTextColor = Color.Black,
            secondaryTextColor = Color(0xFF64748B),
            glassBackgroundColor = Color(0xFFE2E8F0).copy(alpha = 0.6f),
            glassBorderColor = Color(0xFF3B82F6).copy(alpha = 0.3f),
            countTextColor = if (count > 0) Color(0xFF3B82F6) else Color.Black,
            positiveColor = Color.White,
            negativeColor = if (count > 0) Color(0xFFDC2626) else Color.Black.copy(alpha = 0.15f),
            iconContainerColor = Color(0x10000000),
            iconBorderColor = Color(0x15000000),
            iconTintColor = Color.Black,
            incrementGradients = listOf(Color(0xFF3B82F6), Color(0xFF1D4ED8)),
            incrementShadow = Color(0xFF3B82F6),
            decrementGradientsActive = listOf(Color(0xFFFEE2E2), Color(0xFFFECDD3)),
            decrementGradientsInactive = listOf(Color(0xFFF1F5F9), Color(0xFFE2E8F0)),
            decrementShadow = Color(0xFFEF4444),
            resetContainerColor = Color(0xFFFEE2E2),
            resetContentColor = Color(0xFFDC2626),
            resetBorderColor = Color(0xFFFCA5A5),
            sheetBackgroundColor = Color.White
        )
        AppTheme.DARK -> AppThemeColors(
            backgroundGradient = listOf(Color(0xFF0F172A), Color(0xFF020617)),
            headerAccentColor = Color(0xFF60A5FA),
            primaryTextColor = Color.White,
            secondaryTextColor = Color(0xFF94A3B8),
            glassBackgroundColor = Color(0xFF1E293B).copy(alpha = 0.6f),
            glassBorderColor = Color(0xFF3B82F6).copy(alpha = 0.3f),
            countTextColor = if (count > 0) Color(0xFF60A5FA) else Color.White,
            positiveColor = Color.White,
            negativeColor = if (count > 0) Color(0xFFFCA5A5) else Color.White.copy(alpha = 0.2f),
            iconContainerColor = Color(0x33FFFFFF),
            iconBorderColor = Color(0x15FFFFFF),
            iconTintColor = Color.White,
            incrementGradients = listOf(Color(0xFF3B82F6), Color(0xFF1D4ED8)),
            incrementShadow = Color(0xFF3B82F6),
            decrementGradientsActive = listOf(Color(0xFFEF4444).copy(alpha = 0.25f), Color(0xFF7F1D1D).copy(alpha = 0.15f)),
            decrementGradientsInactive = listOf(Color(0xFFEF4444).copy(alpha = 0.05f), Color(0xFF7F1D1D).copy(alpha = 0.03f)),
            decrementShadow = Color(0xFFEF4444),
            resetContainerColor = Color(0xFFEF4444).copy(alpha = 0.15f),
            resetContentColor = Color(0xFFFCA5A5),
            resetBorderColor = Color(0xFFEF4444).copy(alpha = 0.3f),
            sheetBackgroundColor = Color(0xFF0F172A)
        )
        AppTheme.NEON_BLUE -> AppThemeColors(
            backgroundGradient = listOf(Color(0xFF000000), Color(0xFF0A1128)),
            headerAccentColor = Color(0xFF00F0FF),
            primaryTextColor = Color(0xFFE0FFFF),
            secondaryTextColor = Color(0xFF00F0FF).copy(alpha = 0.7f),
            glassBackgroundColor = Color(0xFF00F0FF).copy(alpha = 0.1f),
            glassBorderColor = Color(0xFF00F0FF),
            countTextColor = if (count > 0) Color(0xFF00F0FF) else Color(0xFFE0FFFF),
            positiveColor = Color.Black,
            negativeColor = if (count > 0) Color(0xFFFF0055) else Color(0xFFE0FFFF).copy(alpha = 0.2f),
            iconContainerColor = Color(0xFF00F0FF).copy(alpha = 0.1f),
            iconBorderColor = Color(0xFF00F0FF),
            iconTintColor = Color(0xFF00F0FF),
            incrementGradients = listOf(Color(0xFF00F0FF), Color(0xFF0088FF)),
            incrementShadow = Color(0xFF00F0FF),
            decrementGradientsActive = listOf(Color(0xFFFF0055).copy(alpha = 0.3f), Color(0xFFAA0033).copy(alpha = 0.2f)),
            decrementGradientsInactive = listOf(Color(0xFFFF0055).copy(alpha = 0.05f), Color(0xFFAA0033).copy(alpha = 0.05f)),
            decrementShadow = Color(0xFFFF0055),
            resetContainerColor = Color(0xFFFF0055).copy(alpha = 0.15f),
            resetContentColor = Color(0xFFFF0055),
            resetBorderColor = Color(0xFFFF0055),
            sheetBackgroundColor = Color(0xFF0A1128)
        )
        AppTheme.RED_GAMING -> AppThemeColors(
            backgroundGradient = listOf(Color(0xFF110000), Color(0xFF330000)),
            headerAccentColor = Color(0xFFFF0000),
            primaryTextColor = Color.White,
            secondaryTextColor = Color(0xFFFF8888),
            glassBackgroundColor = Color(0xFFFF0000).copy(alpha = 0.15f),
            glassBorderColor = Color(0xFFFF0000).copy(alpha = 0.5f),
            countTextColor = if (count > 0) Color(0xFFFF0000) else Color.White,
            positiveColor = Color.White,
            negativeColor = if (count > 0) Color(0xFFFF6666) else Color.White.copy(alpha = 0.2f),
            iconContainerColor = Color(0xFFFF0000).copy(alpha = 0.15f),
            iconBorderColor = Color(0xFFFF0000).copy(alpha = 0.5f),
            iconTintColor = Color.White,
            incrementGradients = listOf(Color(0xFFFF0000), Color(0xFFAA0000)),
            incrementShadow = Color(0xFFFF0000),
            decrementGradientsActive = listOf(Color(0xFFFF8888).copy(alpha = 0.3f), Color(0xFFAA4444).copy(alpha = 0.2f)),
            decrementGradientsInactive = listOf(Color(0xFFFF8888).copy(alpha = 0.05f), Color(0xFFAA4444).copy(alpha = 0.05f)),
            decrementShadow = Color(0xFFFF8888),
            resetContainerColor = Color(0xFFFF0000).copy(alpha = 0.15f),
            resetContentColor = Color(0xFFFFAAAA),
            resetBorderColor = Color(0xFFFF0000).copy(alpha = 0.5f),
            sheetBackgroundColor = Color(0xFF220000)
        )
        AppTheme.NEON_GREEN -> AppThemeColors(
            backgroundGradient = listOf(Color(0xFF001100), Color(0xFF003300)),
            headerAccentColor = Color(0xFF00FF00),
            primaryTextColor = Color.White,
            secondaryTextColor = Color(0xFF88FF88),
            glassBackgroundColor = Color(0xFF00FF00).copy(alpha = 0.15f),
            glassBorderColor = Color(0xFF00FF00).copy(alpha = 0.5f),
            countTextColor = if (count > 0) Color(0xFF00FF00) else Color.White,
            positiveColor = Color.White,
            negativeColor = if (count > 0) Color(0xFF66FF66) else Color.White.copy(alpha = 0.2f),
            iconContainerColor = Color(0xFF00FF00).copy(alpha = 0.15f),
            iconBorderColor = Color(0xFF00FF00).copy(alpha = 0.5f),
            iconTintColor = Color.White,
            incrementGradients = listOf(Color(0xFF00FF00), Color(0xFF00AA00)),
            incrementShadow = Color(0xFF00FF00),
            decrementGradientsActive = listOf(Color(0xFF88FF88).copy(alpha = 0.3f), Color(0xFF44AA44).copy(alpha = 0.2f)),
            decrementGradientsInactive = listOf(Color(0xFF88FF88).copy(alpha = 0.05f), Color(0xFF44AA44).copy(alpha = 0.05f)),
            decrementShadow = Color(0xFF88FF88),
            resetContainerColor = Color(0xFF00FF00).copy(alpha = 0.15f),
            resetContentColor = Color(0xFFAAFFAA),
            resetBorderColor = Color(0xFF00FF00).copy(alpha = 0.5f),
            sheetBackgroundColor = Color(0xFF002200)
        )
        AppTheme.GOLD -> AppThemeColors(
            backgroundGradient = listOf(Color(0xFF1A1A00), Color(0xFF333300)),
            headerAccentColor = Color(0xFFFFD700),
            primaryTextColor = Color.White,
            secondaryTextColor = Color(0xFFFFF088),
            glassBackgroundColor = Color(0xFFFFD700).copy(alpha = 0.15f),
            glassBorderColor = Color(0xFFFFD700).copy(alpha = 0.5f),
            countTextColor = if (count > 0) Color(0xFFFFD700) else Color.White,
            positiveColor = Color.Black,
            negativeColor = if (count > 0) Color(0xFFFFE066) else Color.White.copy(alpha = 0.2f),
            iconContainerColor = Color(0xFFFFD700).copy(alpha = 0.15f),
            iconBorderColor = Color(0xFFFFD700).copy(alpha = 0.5f),
            iconTintColor = Color(0xFFFFD700),
            incrementGradients = listOf(Color(0xFFFFD700), Color(0xFFB8860B)),
            incrementShadow = Color(0xFFFFD700),
            decrementGradientsActive = listOf(Color(0xFFFFF088).copy(alpha = 0.3f), Color(0xFFB8860B).copy(alpha = 0.2f)),
            decrementGradientsInactive = listOf(Color(0xFFFFF088).copy(alpha = 0.05f), Color(0xFFB8860B).copy(alpha = 0.05f)),
            decrementShadow = Color(0xFFFFF088),
            resetContainerColor = Color(0xFFFFD700).copy(alpha = 0.15f),
            resetContentColor = Color(0xFFFFF8AA),
            resetBorderColor = Color(0xFFFFD700).copy(alpha = 0.5f),
            sheetBackgroundColor = Color(0xFF222200)
        )
        AppTheme.PURPLE -> AppThemeColors(
            backgroundGradient = listOf(Color(0xFF110022), Color(0xFF220044)),
            headerAccentColor = Color(0xFFaa00ff),
            primaryTextColor = Color(0xFFF3E5F5),
            secondaryTextColor = Color(0xFFD1C4E9),
            glassBackgroundColor = Color(0xFFaa00ff).copy(alpha = 0.2f),
            glassBorderColor = Color(0xFFaa00ff).copy(alpha = 0.5f),
            countTextColor = if (count > 0) Color(0xFFD500F9) else Color(0xFFF3E5F5),
            positiveColor = Color.White,
            negativeColor = if (count > 0) Color(0xFFEA80FC) else Color(0xFFF3E5F5).copy(alpha = 0.2f),
            iconContainerColor = Color(0xFFaa00ff).copy(alpha = 0.15f),
            iconBorderColor = Color(0xFFaa00ff).copy(alpha = 0.5f),
            iconTintColor = Color(0xFFEA80FC),
            incrementGradients = listOf(Color(0xFFaa00ff), Color(0xFF6200ea)),
            incrementShadow = Color(0xFFaa00ff),
            decrementGradientsActive = listOf(Color(0xFFEA80FC).copy(alpha = 0.3f), Color(0xFF6200ea).copy(alpha = 0.2f)),
            decrementGradientsInactive = listOf(Color(0xFFEA80FC).copy(alpha = 0.05f), Color(0xFF6200ea).copy(alpha = 0.05f)),
            decrementShadow = Color(0xFFEA80FC),
            resetContainerColor = Color(0xFFaa00ff).copy(alpha = 0.15f),
            resetContentColor = Color(0xFFE1BEE7),
            resetBorderColor = Color(0xFFaa00ff).copy(alpha = 0.5f),
            sheetBackgroundColor = Color(0xFF1A0033)
        )
    }
}
